/*
 * This source file was generated by the Gradle 'init' task
 */
package org.SantaBike;

public class Main {
    public static void main(String[] args) {
        Cliente cliente = new Cliente("WIL", "Rua A, 123", "123456789");
        System.out.printf("Nome do Cliente %s\n",cliente.getNome());
        //DataBase database = new DataBase();
    }
}
